// ============================================================
// OmniFM: the 24 doors of the Advent calendar (#428)
// ============================================================
// One surprise a day, the same on every server: a music fact, a saying or a
// small riddle (its answer hidden as a spoiler). Every text in the nine
// languages of the website; the door speaks the language of whoever opens
// it (Discord's interaction locale), English when there is none of these.

export const ADVENT_LANGUAGES = Object.freeze(["de", "en", "fr", "es", "it", "pl", "tr", "pt", "nl"]);

/** The labels around a door, per language. */
export const ADVENT_LABELS = Object.freeze({
  de: { door: "Türchen {day}", tip: "Sender-Tipp des Tages", play: "Jetzt spielen", fact: "Wusstest du?", saying: "Für heute", riddle: "Rätsel", answer: "Lösung", noTip: "Heute gibt es keinen Sender-Tipp für deinen Plan.", closed: "Der Adventskalender öffnet vom 1. bis 24. Dezember." },
  en: { door: "Door {day}", tip: "Station tip of the day", play: "Play now", fact: "Did you know?", saying: "For today", riddle: "Riddle", answer: "Answer", noTip: "There is no station tip for your plan today.", closed: "The Advent calendar opens from 1 to 24 December." },
  fr: { door: "Case {day}", tip: "Station du jour", play: "Écouter", fact: "Le savais-tu ?", saying: "Pour aujourd’hui", riddle: "Devinette", answer: "Réponse", noTip: "Pas de station du jour pour ton offre aujourd’hui.", closed: "Le calendrier de l’Avent s’ouvre du 1er au 24 décembre." },
  es: { door: "Ventanita {day}", tip: "Emisora del día", play: "Escuchar ahora", fact: "¿Sabías que…?", saying: "Para hoy", riddle: "Adivinanza", answer: "Respuesta", noTip: "Hoy no hay emisora del día para tu plan.", closed: "El calendario de Adviento abre del 1 al 24 de diciembre." },
  it: { door: "Finestrella {day}", tip: "Stazione del giorno", play: "Ascolta ora", fact: "Lo sapevi?", saying: "Per oggi", riddle: "Indovinello", answer: "Soluzione", noTip: "Oggi non c’è una stazione del giorno per il tuo piano.", closed: "Il calendario dell’Avvento si apre dal 1° al 24 dicembre." },
  pl: { door: "Okienko {day}", tip: "Stacja dnia", play: "Włącz teraz", fact: "Czy wiesz, że…", saying: "Na dziś", riddle: "Zagadka", answer: "Odpowiedź", noTip: "Dziś nie ma stacji dnia dla twojego planu.", closed: "Kalendarz adwentowy otwiera się od 1 do 24 grudnia." },
  tr: { door: "{day}. kapı", tip: "Günün istasyonu", play: "Şimdi çal", fact: "Biliyor muydun?", saying: "Bugün için", riddle: "Bilmece", answer: "Cevap", noTip: "Bugün planın için günün istasyonu yok.", closed: "Advent takvimi 1–24 Aralık arasında açılır." },
  pt: { door: "Janelinha {day}", tip: "Estação do dia", play: "Tocar agora", fact: "Você sabia?", saying: "Para hoje", riddle: "Charada", answer: "Resposta", noTip: "Hoje não há estação do dia para o seu plano.", closed: "O calendário do Advento abre de 1 a 24 de dezembro." },
  nl: { door: "Deurtje {day}", tip: "Zender van de dag", play: "Nu afspelen", fact: "Wist je dat?", saying: "Voor vandaag", riddle: "Raadsel", answer: "Antwoord", noTip: "Vandaag is er geen zender van de dag voor je abonnement.", closed: "De adventskalender gaat open van 1 tot 24 december." },
});

/**
 * The doors 1-24: { kind, text: {lang}, answer?: {lang} }. Facts are well
 * documented ones; "soll"/"reportedly" where history is not sure.
 */
export const ADVENT_DOORS = Object.freeze([
  {
    kind: "fact",
    text: {
      de: "„Stille Nacht, heilige Nacht“ erklang zum ersten Mal am 24. Dezember 1818 in Oberndorf bei Salzburg.",
      en: "“Silent Night” was sung for the first time on 24 December 1818 in Oberndorf near Salzburg.",
      fr: "« Douce nuit » a été chantée pour la première fois le 24 décembre 1818 à Oberndorf, près de Salzbourg.",
      es: "«Noche de paz» se cantó por primera vez el 24 de diciembre de 1818 en Oberndorf, cerca de Salzburgo.",
      it: "«Astro del ciel» (Stille Nacht) fu cantata per la prima volta il 24 dicembre 1818 a Oberndorf, vicino a Salisburgo.",
      pl: "Kolęda „Cicha noc” zabrzmiała po raz pierwszy 24 grudnia 1818 roku w Oberndorfie pod Salzburgiem.",
      tr: "“Sessiz Gece” ilk kez 24 Aralık 1818’de Salzburg yakınlarındaki Oberndorf’ta söylendi.",
      pt: "“Noite Feliz” foi cantada pela primeira vez em 24 de dezembro de 1818 em Oberndorf, perto de Salzburgo.",
      nl: "„Stille Nacht” werd voor het eerst gezongen op 24 december 1818 in Oberndorf bij Salzburg.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Ich habe Tasten, aber öffne kein Schloss. Was bin ich?",
      en: "I have keys but open no locks. What am I?",
      fr: "J’ai des touches mais je n’ouvre aucune serrure. Qui suis-je ?",
      es: "Tengo teclas pero no abro ninguna cerradura. ¿Qué soy?",
      it: "Ho dei tasti ma non apro nessuna serratura. Cosa sono?",
      pl: "Mam klawisze, ale nie otwieram żadnych zamków. Czym jestem?",
      tr: "Tuşlarım var ama hiçbir kilidi açmam. Ben neyim?",
      pt: "Tenho teclas, mas não abro nenhuma fechadura. O que sou?",
      nl: "Ik heb toetsen maar open geen enkel slot. Wat ben ik?",
    },
    answer: { de: "Ein Klavier.", en: "A piano.", fr: "Un piano.", es: "Un piano.", it: "Un pianoforte.", pl: "Pianino.", tr: "Bir piyano.", pt: "Um piano.", nl: "Een piano." },
  },
  {
    kind: "saying",
    text: {
      de: "Musik ist die beste Heizung an kalten Tagen: aufdrehen und wärmen lassen.",
      en: "Music is the best heating on cold days: turn it up and let it warm you.",
      fr: "La musique est le meilleur chauffage par temps froid : monte le son et laisse-toi réchauffer.",
      es: "La música es la mejor calefacción en los días fríos: súbele el volumen y deja que te caliente.",
      it: "La musica è il miglior riscaldamento nei giorni freddi: alza il volume e lasciati scaldare.",
      pl: "Muzyka to najlepsze ogrzewanie w zimne dni: podkręć głośność i daj się rozgrzać.",
      tr: "Soğuk günlerde en iyi ısıtıcı müziktir: sesini aç ve seni ısıtsın.",
      pt: "Música é o melhor aquecedor nos dias frios: aumente o volume e deixe ela te aquecer.",
      nl: "Muziek is de beste verwarming op koude dagen: zet hem harder en laat je opwarmen.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "„Jingle Bells“ war 1965 das erste Lied, das im Weltall gespielt wurde: Die Crew von Gemini 6 spielte es auf Mundharmonika und Glöckchen.",
      en: "In 1965 “Jingle Bells” became the first song played in space: the Gemini 6 crew played it on a harmonica and bells.",
      fr: "En 1965, « Jingle Bells » est devenue la première chanson jouée dans l’espace : l’équipage de Gemini 6 l’a jouée à l’harmonica et aux clochettes.",
      es: "En 1965, «Jingle Bells» fue la primera canción tocada en el espacio: la tripulación del Gemini 6 la tocó con una armónica y cascabeles.",
      it: "Nel 1965 «Jingle Bells» fu la prima canzone suonata nello spazio: l’equipaggio del Gemini 6 la suonò con armonica e campanelli.",
      pl: "W 1965 roku „Jingle Bells” była pierwszą piosenką zagraną w kosmosie: załoga Gemini 6 zagrała ją na harmonijce i dzwoneczkach.",
      tr: "1965’te “Jingle Bells” uzayda çalınan ilk şarkı oldu: Gemini 6 mürettebatı onu mızıka ve çıngıraklarla çaldı.",
      pt: "Em 1965, “Jingle Bells” foi a primeira música tocada no espaço: a tripulação da Gemini 6 tocou com gaita e sininhos.",
      nl: "In 1965 werd „Jingle Bells” het eerste lied dat in de ruimte werd gespeeld: de bemanning van Gemini 6 speelde het op mondharmonica en belletjes.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Was hat einen Hals, aber keinen Kopf?",
      en: "What has a neck but no head?",
      fr: "Qu’est-ce qui a un cou mais pas de tête ?",
      es: "¿Qué tiene cuello pero no cabeza?",
      it: "Che cosa ha il collo ma non la testa?",
      pl: "Co ma szyjkę, ale nie ma głowy?",
      tr: "Boynu var ama başı yok. Nedir?",
      pt: "O que tem pescoço, mas não tem cabeça?",
      nl: "Wat heeft een hals maar geen hoofd?",
    },
    answer: { de: "Eine Flasche oder eine Gitarre.", en: "A bottle or a guitar.", fr: "Une bouteille.", es: "Una botella.", it: "Una bottiglia.", pl: "Butelka.", tr: "Bir şişe.", pt: "Uma garrafa.", nl: "Een fles of een gitaar." },
  },
  {
    kind: "saying",
    text: {
      de: "Ein guter Song ist wie eine Tasse Tee: Er wärmt von innen.",
      en: "A good song is like a cup of tea: it warms you from the inside.",
      fr: "Une bonne chanson, c’est comme une tasse de thé : elle réchauffe de l’intérieur.",
      es: "Una buena canción es como una taza de té: calienta por dentro.",
      it: "Una bella canzone è come una tazza di tè: scalda da dentro.",
      pl: "Dobra piosenka jest jak filiżanka herbaty: rozgrzewa od środka.",
      tr: "İyi bir şarkı bir fincan çay gibidir: içini ısıtır.",
      pt: "Uma boa música é como uma xícara de chá: aquece por dentro.",
      nl: "Een goed nummer is als een kop thee: het warmt je van binnen.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "An Heiligabend 1906 soll Reginald Fessenden eine der ersten Radiosendungen mit Sprache und Musik gesendet haben, samt „O Holy Night“ auf der Geige.",
      en: "On Christmas Eve 1906 Reginald Fessenden reportedly sent one of the first radio broadcasts with speech and music, including “O Holy Night” on the violin.",
      fr: "La veille de Noël 1906, Reginald Fessenden aurait diffusé l’une des premières émissions de radio avec parole et musique, dont « O Holy Night » au violon.",
      es: "En la Nochebuena de 1906, Reginald Fessenden habría emitido una de las primeras transmisiones de radio con voz y música, incluido «O Holy Night» al violín.",
      it: "La vigilia di Natale del 1906 Reginald Fessenden avrebbe trasmesso una delle prime trasmissioni radio con voce e musica, con «O Holy Night» al violino.",
      pl: "W Wigilię 1906 roku Reginald Fessenden miał nadać jedną z pierwszych audycji radiowych z mową i muzyką, w tym „O Holy Night” na skrzypcach.",
      tr: "Anlatılanlara göre Reginald Fessenden 1906 Noel arifesinde konuşma ve müzik içeren ilk radyo yayınlarından birini yaptı; kemanla “O Holy Night” da çaldı.",
      pt: "Na véspera de Natal de 1906, Reginald Fessenden teria feito uma das primeiras transmissões de rádio com voz e música, incluindo “O Holy Night” no violino.",
      nl: "Op kerstavond 1906 zou Reginald Fessenden een van de eerste radio-uitzendingen met spraak en muziek hebben uitgezonden, met „O Holy Night” op viool.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Je mehr du davon wegnimmst, desto größer wird es. Was ist das?",
      en: "The more you take away, the bigger it gets. What is it?",
      fr: "Plus on en retire, plus il devient grand. Qu’est-ce que c’est ?",
      es: "Cuanto más le quitas, más grande se hace. ¿Qué es?",
      it: "Più ne togli, più diventa grande. Che cos’è?",
      pl: "Im więcej z niej zabierasz, tym większa się staje. Co to jest?",
      tr: "Ondan aldıkça büyür. Nedir?",
      pt: "Quanto mais você tira, maior ele fica. O que é?",
      nl: "Hoe meer je ervan weghaalt, hoe groter het wordt. Wat is het?",
    },
    answer: { de: "Ein Loch.", en: "A hole.", fr: "Un trou.", es: "Un agujero.", it: "Un buco.", pl: "Dziura.", tr: "Bir çukur.", pt: "Um buraco.", nl: "Een gat." },
  },
  {
    kind: "saying",
    text: {
      de: "Heute ist ein guter Tag, um einen neuen Sender zu entdecken.",
      en: "Today is a good day to discover a new station.",
      fr: "Aujourd’hui est un bon jour pour découvrir une nouvelle station.",
      es: "Hoy es un buen día para descubrir una emisora nueva.",
      it: "Oggi è un buon giorno per scoprire una nuova stazione.",
      pl: "Dziś to dobry dzień, by odkryć nową stację.",
      tr: "Bugün yeni bir istasyon keşfetmek için güzel bir gün.",
      pt: "Hoje é um bom dia para descobrir uma estação nova.",
      nl: "Vandaag is een goede dag om een nieuwe zender te ontdekken.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "Bing Crosbys „White Christmas“ gilt als eine der meistverkauften Singles aller Zeiten.",
      en: "Bing Crosby’s “White Christmas” is considered one of the best-selling singles of all time.",
      fr: "« White Christmas » de Bing Crosby est considéré comme l’un des singles les plus vendus de tous les temps.",
      es: "«White Christmas» de Bing Crosby se considera uno de los sencillos más vendidos de todos los tiempos.",
      it: "«White Christmas» di Bing Crosby è considerato uno dei singoli più venduti di tutti i tempi.",
      pl: "„White Christmas” Binga Crosby’ego uchodzi za jeden z najlepiej sprzedających się singli wszech czasów.",
      tr: "Bing Crosby’nin “White Christmas” şarkısı tüm zamanların en çok satan single’larından biri sayılır.",
      pt: "“White Christmas”, de Bing Crosby, é considerado um dos singles mais vendidos de todos os tempos.",
      nl: "„White Christmas” van Bing Crosby geldt als een van de best verkochte singles aller tijden.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Ich rausche ohne Mund und wohne zwischen zwei Sendern. Was bin ich?",
      en: "I hiss without a mouth and live between two stations. What am I?",
      fr: "Je grésille sans bouche et je vis entre deux stations. Qui suis-je ?",
      es: "Susurro sin boca y vivo entre dos emisoras. ¿Qué soy?",
      it: "Fruscio senza bocca e vivo tra due stazioni. Cosa sono?",
      pl: "Szumię bez ust i mieszkam między dwiema stacjami. Czym jestem?",
      tr: "Ağzım yok ama hışırdarım, iki istasyon arasında yaşarım. Ben neyim?",
      pt: "Chio sem ter boca e moro entre duas estações. O que sou?",
      nl: "Ik ruis zonder mond en woon tussen twee zenders. Wat ben ik?",
    },
    answer: { de: "Das Rauschen im Radio.", en: "Radio static.", fr: "Le grésillement de la radio.", es: "La estática de la radio.", it: "Il fruscio della radio.", pl: "Szum radia.", tr: "Radyo paraziti.", pt: "O chiado do rádio.", nl: "Het geruis van de radio." },
  },
  {
    kind: "saying",
    text: {
      de: "Lieblingslied an, Handy weg, fünf Minuten nur zuhören.",
      en: "Favourite song on, phone away, five minutes of just listening.",
      fr: "Ta chanson préférée, le téléphone de côté, cinq minutes d’écoute rien que pour toi.",
      es: "Tu canción favorita, el móvil a un lado y cinco minutos solo para escuchar.",
      it: "La tua canzone preferita, il telefono da parte, cinque minuti solo per ascoltare.",
      pl: "Ulubiona piosenka, telefon na bok, pięć minut samego słuchania.",
      tr: "En sevdiğin şarkıyı aç, telefonu bırak, beş dakika sadece dinle.",
      pt: "Sua música favorita, o celular de lado, cinco minutos só ouvindo.",
      nl: "Lievelingsnummer aan, telefoon weg, vijf minuten alleen maar luisteren.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "„Last Christmas“ von Wham! erschien 1984.",
      en: "Wham!’s “Last Christmas” came out in 1984.",
      fr: "« Last Christmas » de Wham! est sorti en 1984.",
      es: "«Last Christmas» de Wham! salió en 1984.",
      it: "«Last Christmas» dei Wham! è uscita nel 1984.",
      pl: "„Last Christmas” zespołu Wham! ukazało się w 1984 roku.",
      tr: "Wham!’in “Last Christmas” şarkısı 1984’te çıktı.",
      pt: "“Last Christmas”, do Wham!, foi lançada em 1984.",
      nl: "„Last Christmas” van Wham! verscheen in 1984.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Was wird nasser, je mehr es trocknet?",
      en: "What gets wetter the more it dries?",
      fr: "Qu’est-ce qui devient plus mouillé à mesure qu’il sèche ?",
      es: "¿Qué se moja más cuanto más seca?",
      it: "Che cosa si bagna di più più asciuga?",
      pl: "Co robi się coraz bardziej mokre, im więcej suszy?",
      tr: "Kuruladıkça daha çok ıslanan şey nedir?",
      pt: "O que fica mais molhado quanto mais seca?",
      nl: "Wat wordt natter naarmate het meer afdroogt?",
    },
    answer: { de: "Ein Handtuch.", en: "A towel.", fr: "Une serviette.", es: "Una toalla.", it: "Un asciugamano.", pl: "Ręcznik.", tr: "Bir havlu.", pt: "Uma toalha.", nl: "Een handdoek." },
  },
  {
    kind: "saying",
    text: {
      de: "Kleiner Tipp: Sag heute jemandem, welcher Song dich an ihn oder sie erinnert.",
      en: "Little tip: tell someone today which song reminds you of them.",
      fr: "Petit conseil : dis aujourd’hui à quelqu’un quelle chanson te fait penser à lui ou à elle.",
      es: "Pequeño consejo: dile hoy a alguien qué canción te recuerda a esa persona.",
      it: "Piccolo consiglio: di’ oggi a qualcuno quale canzone ti fa pensare a lui o a lei.",
      pl: "Mała rada: powiedz dziś komuś, która piosenka kojarzy ci się z tą osobą.",
      tr: "Küçük bir öneri: bugün birine hangi şarkının sana onu hatırlattığını söyle.",
      pt: "Dica: conte hoje para alguém qual música faz você lembrar dessa pessoa.",
      nl: "Kleine tip: vertel iemand vandaag welk nummer je aan diegene doet denken.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "Ein Radio-Stream mit 128 kbit/s braucht in einer Stunde etwa 58 Megabyte.",
      en: "A 128 kbit/s radio stream uses about 58 megabytes an hour.",
      fr: "Un flux radio à 128 kbit/s consomme environ 58 mégaoctets par heure.",
      es: "Una emisión de radio a 128 kbit/s gasta unos 58 megabytes por hora.",
      it: "Uno stream radio a 128 kbit/s consuma circa 58 megabyte all’ora.",
      pl: "Strumień radiowy 128 kbit/s zużywa około 58 megabajtów na godzinę.",
      tr: "128 kbit/s’lik bir radyo yayını saatte yaklaşık 58 megabayt harcar.",
      pt: "Um stream de rádio a 128 kbit/s gasta cerca de 58 megabytes por hora.",
      nl: "Een radiostream van 128 kbit/s gebruikt ongeveer 58 megabyte per uur.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Ich habe Zähne, aber ich beiße nie. Was bin ich?",
      en: "I have teeth but never bite. What am I?",
      fr: "J’ai des dents mais je ne mords jamais. Qui suis-je ?",
      es: "Tengo dientes pero nunca muerdo. ¿Qué soy?",
      it: "Ho i denti ma non mordo mai. Cosa sono?",
      pl: "Mam zęby, ale nigdy nie gryzę. Czym jestem?",
      tr: "Dişlerim var ama asla ısırmam. Ben neyim?",
      pt: "Tenho dentes, mas nunca mordo. O que sou?",
      nl: "Ik heb tanden maar bijt nooit. Wat ben ik?",
    },
    answer: { de: "Ein Kamm.", en: "A comb.", fr: "Un peigne.", es: "Un peine.", it: "Un pettine.", pl: "Grzebień.", tr: "Bir tarak.", pt: "Um pente.", nl: "Een kam." },
  },
  {
    kind: "saying",
    text: {
      de: "Die schönsten Momente haben oft einen Soundtrack.",
      en: "The best moments often have a soundtrack.",
      fr: "Les plus beaux moments ont souvent une bande-son.",
      es: "Los mejores momentos suelen tener banda sonora.",
      it: "I momenti più belli hanno spesso una colonna sonora.",
      pl: "Najpiękniejsze chwile często mają swoją ścieżkę dźwiękową.",
      tr: "En güzel anların çoğu zaman bir film müziği vardır.",
      pt: "Os melhores momentos costumam ter trilha sonora.",
      nl: "De mooiste momenten hebben vaak een soundtrack.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "Die Tonsilben „Do, Re, Mi“ gehen auf den Mönch Guido von Arezzo im 11. Jahrhundert zurück.",
      en: "The syllables “Do, Re, Mi” go back to the monk Guido of Arezzo in the 11th century.",
      fr: "Les syllabes « do, ré, mi » remontent au moine Guido d’Arezzo, au XIᵉ siècle.",
      es: "Las sílabas «do, re, mi» se remontan al monje Guido de Arezzo, en el siglo XI.",
      it: "Le sillabe «do, re, mi» risalgono al monaco Guido d’Arezzo, nell’XI secolo.",
      pl: "Sylaby „do, re, mi” pochodzą od mnicha Guida z Arezzo z XI wieku.",
      tr: "“Do, re, mi” heceleri 11. yüzyılda keşiş Arezzolu Guido’ya dayanır.",
      pt: "As sílabas “dó, ré, mi” remontam ao monge Guido d’Arezzo, no século XI.",
      nl: "De lettergrepen „do, re, mi” gaan terug op de monnik Guido van Arezzo in de 11e eeuw.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Was gehört dir, wird aber von anderen öfter benutzt als von dir?",
      en: "What belongs to you, but others use it more than you do?",
      fr: "Qu’est-ce qui t’appartient mais que les autres utilisent plus que toi ?",
      es: "¿Qué es tuyo pero los demás lo usan más que tú?",
      it: "Che cosa è tuo, ma gli altri lo usano più di te?",
      pl: "Co należy do ciebie, ale inni używają tego częściej niż ty?",
      tr: "Senindir ama başkaları senden daha çok kullanır. Nedir?",
      pt: "O que é seu, mas os outros usam mais do que você?",
      nl: "Wat is van jou, maar gebruiken anderen vaker dan jij?",
    },
    answer: { de: "Dein Name.", en: "Your name.", fr: "Ton prénom.", es: "Tu nombre.", it: "Il tuo nome.", pl: "Twoje imię.", tr: "Adın.", pt: "Seu nome.", nl: "Je naam." },
  },
  {
    kind: "saying",
    text: {
      de: "Winterabende und gutes Radio: eine Freundschaft fürs Leben.",
      en: "Winter evenings and good radio: a friendship for life.",
      fr: "Soirées d’hiver et bonne radio : une amitié pour la vie.",
      es: "Tardes de invierno y buena radio: una amistad para toda la vida.",
      it: "Serate d’inverno e buona radio: un’amicizia per la vita.",
      pl: "Zimowe wieczory i dobre radio: przyjaźń na całe życie.",
      tr: "Kış akşamları ve iyi radyo: ömürlük bir dostluk.",
      pt: "Noites de inverno e um bom rádio: uma amizade para a vida toda.",
      nl: "Winteravonden en goede radio: een vriendschap voor het leven.",
    },
  },
  {
    kind: "fact",
    text: {
      de: "Das Wort „Radio“ kommt vom lateinischen „radius“, dem Strahl.",
      en: "The word “radio” comes from the Latin “radius”, a ray.",
      fr: "Le mot « radio » vient du latin « radius », le rayon.",
      es: "La palabra «radio» viene del latín «radius», el rayo.",
      it: "La parola «radio» viene dal latino «radius», il raggio.",
      pl: "Słowo „radio” pochodzi od łacińskiego „radius”, czyli promień.",
      tr: "“Radyo” kelimesi Latince “ışın” anlamına gelen “radius”tan gelir.",
      pt: "A palavra “rádio” vem do latim “radius”, o raio.",
      nl: "Het woord „radio” komt van het Latijnse „radius”, de straal.",
    },
  },
  {
    kind: "riddle",
    text: {
      de: "Was reist um die ganze Welt und bleibt dabei immer in seiner Ecke?",
      en: "What travels around the world but stays in its corner?",
      fr: "Qu’est-ce qui fait le tour du monde en restant dans son coin ?",
      es: "¿Qué da la vuelta al mundo sin moverse de su esquina?",
      it: "Che cosa fa il giro del mondo restando sempre nel suo angolo?",
      pl: "Co podróżuje dookoła świata, a zawsze zostaje w swoim rogu?",
      tr: "Dünyanın etrafını dolaşır ama hep köşesinde kalır. Nedir?",
      pt: "O que viaja o mundo inteiro sem sair do seu canto?",
      nl: "Wat reist de hele wereld rond maar blijft altijd in zijn hoekje?",
    },
    answer: { de: "Eine Briefmarke.", en: "A stamp.", fr: "Un timbre.", es: "Un sello.", it: "Un francobollo.", pl: "Znaczek pocztowy.", tr: "Bir pul.", pt: "Um selo.", nl: "Een postzegel." },
  },
  {
    kind: "saying",
    text: {
      de: "Frohe Weihnachten! Danke, dass ihr mit OmniFM hört.",
      en: "Merry Christmas! Thank you for listening with OmniFM.",
      fr: "Joyeux Noël ! Merci d’écouter avec OmniFM.",
      es: "¡Feliz Navidad! Gracias por escuchar con OmniFM.",
      it: "Buon Natale! Grazie di ascoltare con OmniFM.",
      pl: "Wesołych Świąt! Dziękujemy, że słuchacie z OmniFM.",
      tr: "Mutlu Noeller! OmniFM ile dinlediğiniz için teşekkürler.",
      pt: "Feliz Natal! Obrigado por ouvir com o OmniFM.",
      nl: "Vrolijk kerstfeest! Bedankt dat jullie met OmniFM luisteren.",
    },
  },
]);
